{
    'name': "Task management",
    'summary': """
        The module is designed to calculate the time for completed tasks.""",
    'author': "Aleksander Huryn",
    'category': 'Helpdesk',
    'version': '15.0.1.0.1',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/sg_tm_groups.xml',
        'security/ir.model.access.csv',
        'security/sg_tm_security.xml',
        'wizard/sg_tm_change_res_employee_wizard_views.xml',
        'wizard/sg_tm_set_time_wizard_views.xml',
        'views/sg_tm_menu.xml',
        'views/sg_tm_project_views.xml',
        'views/sg_tm_employee_views.xml',
        'views/sg_tm_price_views.xml',
        'views/sg_tm_task_history_views.xml',
        'views/sg_tm_billing_views.xml',
        'views/sg_tm_task_views.xml',
        'views/res_partner_views.xml',
        'report/sg_tm_employee_report.xml',
        'report/sg_tm_employee_template.xml',
    ],
    'demo': [
        'data/sg_tm_user_data.xml',
        'data/sg_tm_partner_data.xml',
        'data/sg_tm_currency_data.xml',
        'data/sg_tm_employee_data.xml',
        'data/sg_tm_project_data.xml',
        'data/sg_tm_price_data.xml',
        'demo/sg_tm_task_demo.xml',
        'demo/sg_tm_billing_demo.xml',
    ],
    'images': ['static/description/baner.jpg', 'static/description/icon.jpg']
}
